"""
Phase 4 — validate the STARS -> GRI mapping table
=================================================

WHY THIS EXISTS
    CLAUDE.md §3: the mapping table is built by hand against the real standards
    and is NEVER generated by an LLM, because a fabricated mapping is an
    integrity failure in an ESG tool.

    The rows in stars_gri_mapping.csv were drafted with LLM assistance, so they
    are all marked review_status = "proposed" and are NOT usable as fact until a
    human confirms each one against the standard. This script is the machinery
    that makes that safe:

      1. Every gri_disclosure must exist in standards/gri_disclosures.json,
         which was built from retrieved GRI source text. An invented disclosure
         number is a HARD ERROR - it cannot reach the report.

      2. Every stars_credit / stars_field must exist in esg_master_dataset.csv.
         A mapping to a field that was never scraped is a HARD ERROR.

      3. report_ready() returns ONLY confirmed rows. Phase 5 must call that, so
         an unreviewed row can never be cited in generated prose.

    So the LLM can propose, but only verified-on-both-sides, human-confirmed
    rows can ever be published. Same principle as the number injection: the
    unsafe path is closed by construction, not by discipline.

REVIEW WORKFLOW (this is the human step - it cannot be automated away)
    Open mapping/stars_gri_mapping.csv. For each row, read the GRI disclosure in
    standards/gri/ or on globalreporting.org, decide, then set review_status to:
        confirmed  - the mapping holds as described
        rejected   - it does not; add why in the caveat column
    Leave "proposed" for anything not yet checked. Re-run this script.

RUN
    python validate_mapping.py            (from mapping/)
"""

import json
import pathlib
import sys

import pandas as pd

HERE = pathlib.Path(__file__).parent
MAPPING = HERE / "stars_gri_mapping.csv"
GRI_JSON = HERE.parent / "standards" / "gri_disclosures.json"
MASTER = HERE.parent / "Combined_universities_data" / "esg_master_dataset.csv"

VALID_RELATIONSHIPS = {
    "equivalent",      # near 1:1 in definition and unit
    "component",       # STARS field is a constituent of the GRI disclosure
    "intensity",       # STARS field is a ratio matching a GRI intensity disclosure
    "partial",         # overlaps but definitions differ - must be footnoted
    "gap_gri_side",    # GRI asks for it, STARS does not collect it
    "gap_stars_side",  # STARS collects it, GRI has no slot for it
}
VALID_STATUS = {"proposed", "confirmed", "rejected"}
GAP_RELATIONSHIPS = {"gap_gri_side", "gap_stars_side"}


def blank(v) -> bool:
    return pd.isna(v) or str(v).strip() in ("", "*")


def load():
    for p in (MAPPING, GRI_JSON, MASTER):
        if not p.exists():
            sys.exit(f"[stop] missing {p}")
    mapping = pd.read_csv(MAPPING)
    gri = json.loads(GRI_JSON.read_text(encoding="utf-8"))
    master = pd.read_csv(MASTER)
    return mapping, gri, master


def known_disclosures(gri: dict) -> dict:
    out = {}
    for std, body in gri["standards"].items():
        for num, title in body["disclosures"].items():
            out[num] = (std, title)
    return out


def validate(mapping, gri, master):
    disclosures = known_disclosures(gri)
    credits = set(master.credit_code.dropna())
    fields = set(zip(master.credit_code, master.field.fillna("*")))
    errors, warnings = [], []

    for i, r in mapping.iterrows():
        line = i + 2  # +1 for header, +1 for 1-indexing
        rel = str(r.relationship).strip()

        if rel not in VALID_RELATIONSHIPS:
            errors.append(f"line {line}: unknown relationship {rel!r}")
        if str(r.review_status).strip() not in VALID_STATUS:
            errors.append(f"line {line}: unknown review_status {r.review_status!r}")

        # --- GRI side ----------------------------------------------------
        if rel == "gap_stars_side":
            if not blank(r.gri_disclosure):
                errors.append(f"line {line}: gap_stars_side must have no gri_disclosure")
        else:
            if blank(r.gri_disclosure):
                errors.append(f"line {line}: missing gri_disclosure")
            else:
                num = str(r.gri_disclosure).strip()
                if num not in disclosures:
                    errors.append(
                        f"line {line}: GRI disclosure {num!r} does not exist in "
                        f"gri_disclosures.json - INVENTED OR MISTYPED")
                else:
                    std, _ = disclosures[num]
                    if str(r.gri_standard).strip() != std:
                        errors.append(
                            f"line {line}: {num} belongs to {std}, "
                            f"not {r.gri_standard!r}")

        # --- STARS side --------------------------------------------------
        if rel == "gap_gri_side":
            if not blank(r.stars_credit):
                errors.append(f"line {line}: gap_gri_side must have no stars_credit")
        else:
            code = str(r.stars_credit).strip()
            if blank(r.stars_credit):
                errors.append(f"line {line}: missing stars_credit")
            elif code not in credits:
                errors.append(
                    f"line {line}: STARS credit {code!r} is not in the dataset")
            elif not blank(r.stars_field):
                if (code, str(r.stars_field).strip()) not in fields:
                    errors.append(
                        f"line {line}: field {str(r.stars_field)[:50]!r} does not "
                        f"exist under {code} - INVENTED OR MISTYPED")

        # --- quality nudges ----------------------------------------------
        if rel == "partial" and blank(r.caveat):
            warnings.append(
                f"line {line}: 'partial' with no caveat - a partial mapping "
                f"without a stated difference is not usable")

    return errors, warnings


def report_ready(mapping: pd.DataFrame) -> pd.DataFrame:
    """The ONLY mapping rows Phase 5 may cite. Confirmed, non-gap rows."""
    return mapping[(mapping.review_status.str.strip() == "confirmed")
                   & (~mapping.relationship.isin(GAP_RELATIONSHIPS))]


def main():
    mapping, gri, master = load()
    print(f"[load] {len(mapping)} mapping rows")
    print(f"[load] {sum(len(s['disclosures']) for s in gri['standards'].values())} "
          f"GRI disclosures across {len(gri['standards'])} standards "
          f"(retrieved {gri['retrieved']})")
    print(f"[load] {master.credit_code.nunique()} STARS credits, "
          f"{master.field.nunique()} distinct fields")

    errors, warnings = validate(mapping, gri, master)

    print("\n--- validation ---")
    if errors:
        print(f"  {len(errors)} ERROR(S):")
        for e in errors:
            print(f"    ✗ {e}")
    else:
        print("  ✓ every GRI disclosure exists in the retrieved standards")
        print("  ✓ every STARS credit and field exists in the dataset")
    for w in warnings:
        print(f"    ! {w}")

    print("\n--- review status ---")
    for status, n in mapping.review_status.value_counts().items():
        print(f"  {status:12} {n:4}")

    print("\n--- relationship types ---")
    for rel, n in mapping.relationship.value_counts().items():
        print(f"  {rel:16} {n:4}")

    ready = report_ready(mapping)
    print(f"\n--- report-ready rows: {len(ready)} ---")
    if ready.empty:
        print("  NONE. Nothing has been human-confirmed yet, so Phase 5 must not")
        print("  cite any GRI mapping. This is the correct state before review.")

    # ---------- the research finding ----------
    gaps_gri = mapping[mapping.relationship == "gap_gri_side"]
    gaps_stars = mapping[mapping.relationship == "gap_stars_side"]
    print(f"\n--- gaps: GRI asks, STARS cannot answer ({len(gaps_gri)}) ---")
    for _, r in gaps_gri.iterrows():
        print(f"  {r.gri_disclosure:8} {str(r.rationale)[:64]}")
    print(f"\n--- gaps: STARS collects, GRI has no slot ({len(gaps_stars)}) ---")
    for _, r in gaps_stars.iterrows():
        print(f"  {r.stars_credit:8} {str(r.rationale)[:64]}")

    # ---------- coverage of the numeric data ----------
    mapped_fields = set(
        zip(mapping.stars_credit.astype(str).str.strip(),
            mapping.stars_field.astype(str).str.strip()))
    nums = master[(master.value_type == "number")
                  & ~master.field.astype(str).str.startswith("Points earned")]
    uniq = nums[["credit_code", "field"]].drop_duplicates()
    hit = sum((c, f) in mapped_fields for c, f in uniq.itertuples(index=False))
    print(f"\n--- numeric field coverage ---")
    print(f"  {hit} of {len(uniq)} distinct numeric STARS fields have a proposed "
          f"GRI target ({hit / len(uniq) * 100:.0f}%)")
    print("  (low is expected: many are denominators like FTE enrollment, or")
    print("   STARS-internal indicators with no GRI analogue)")

    if errors:
        sys.exit(1)


if __name__ == "__main__":
    main()
