"""
Phase 5b — the narrative writer backends
========================================

WHAT THIS IS FOR

    This is the ONLY place in the project where a language model produces text
    that ends up in the report. Everything else — the scraped figures, the
    mapping, the content index — is mechanical. Keeping the model behind one
    small, swappable interface is what makes that claim checkable: if you want
    to know where the LLM touches the report, it is this file and nothing else.

WHAT THE MODEL IS AND IS NOT ALLOWED TO DO

    Allowed:     choose the sentences, the order, the emphasis, the register.
    Not allowed: emit a single figure.

    The model writes `{{ scope1_total }}` and code substitutes 6,215.78 later
    (CLAUDE.md §3, "non-hallucinable by construction"). This file only enforces
    the rule in the prompt; build_narrative.py enforces it mechanically after
    the fact, which is the half that actually counts.

THE BACKENDS

    gemini  (preferred)  Google Gemini via the google-genai SDK. Chosen because
                         Google AI Studio issues free API keys with no card —
                         which matters for a student project — and because
                         freellm.net, the free-API directory Hakim's supervisor
                         recommended, lists Gemini among its providers.

    stub    (fallback)   Deterministic canned prose, no network, no key. It
                         emits real `{{ tokens }}`, so the substitution and the
                         number-safety checks are exercised end to end without
                         anyone having an API key. The whole pipeline is
                         testable offline.

    rogue   (test only)  Deliberately writes a bare number instead of a token.
                         Exists so tests/test_narrative_safety.py can PROVE the
                         safety check fires, the same way
                         test_validator_catches_fabrication.py proves the
                         mapping validator fires. A guarantee nobody has tried
                         to break is not a guarantee.

WHY models.generate_content AND NOT interactions.create

    The SDK now offers both. `client.interactions.create(...)` is the newer
    surface, but Google's published Python reference documents
    `system_instruction` and `temperature` against `models.generate_content`,
    and this job needs both: a hard system rule about numbers, and a low
    temperature so a report regenerates roughly the same way twice. Verified
    against googleapis.github.io/python-genai on 2026-08-21 rather than
    recalled — CLAUDE.md §12.
"""

from __future__ import annotations

import os

# Gemini's free tier covers the Flash models; Pro sits behind billing. This is
# the one string to change when Google renames things — and they do, often. If
# it is wrong the backend says so and lists what the key can actually see,
# rather than failing with a bare 404.
DEFAULT_GEMINI_MODEL = "gemini-3.7-flash"

# Low but not zero. Zero makes the prose mechanical and repetitive across the
# eight sections; this keeps it readable while staying close to reproducible.
TEMPERATURE = 0.3


class WriterError(RuntimeError):
    """Raised when a backend cannot produce text. Never returns empty prose."""


class StubWriter:
    """Canned prose that still exercises the token machinery.

    Deliberately terse and obviously synthetic — nobody should mistake stub
    output for a finished report — but it emits the first few tokens it was
    handed, so substitution, StrictUndefined and the digit scan all run.
    """

    name = "stub"
    needs_key = False

    def write(self, system: str, prompt: str, tokens: list[str]) -> str:
        preamble = ("This section was generated by the offline stub backend, "
                    "so its wording carries no meaning; only the substitution "
                    "path is being exercised.")
        if not tokens:
            return preamble
        # Two things this deliberately avoids, both learned by getting them
        # wrong. Do not wrap the lines: a wrap can split `{{ token }}` across a
        # newline, which Jinja tolerates but a real model would not produce.
        # And do not print the token NAME in the prose: names like
        # `op6_annual_scope_1_ghg_emissions` carry digits, which the number
        # audit then correctly reports as unaccounted-for text.
        lines = [f"A reported value here was {{{{ {t} }}}}." for t in tokens[:4]]
        return preamble + "\n" + "\n".join(lines)


class RogueWriter:
    """A backend that breaks the rule on purpose. Used only by the tests."""

    name = "rogue"
    needs_key = False

    def write(self, system: str, prompt: str, tokens: list[str]) -> str:
        return ("The university reduced its emissions by 42,000 metric tons "
                "last year, a fall of 17 percent.")


class GeminiWriter:
    """Google Gemini through the official google-genai SDK."""

    name = "gemini"
    needs_key = True

    def __init__(self, model: str = DEFAULT_GEMINI_MODEL):
        try:
            from google import genai
            from google.genai import types
        except ImportError as exc:                       # pragma: no cover
            raise WriterError(
                "google-genai is not installed. Run: pip install google-genai"
            ) from exc

        key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
        if not key:
            raise WriterError(
                "No API key. Get a free one at https://aistudio.google.com/apikey "
                "then add it to the project's .env file as:\n"
                "    GEMINI_API_KEY=your-key-here")

        self._genai = genai
        self._types = types
        self._client = genai.Client(api_key=key)
        self.model = model

    def available_models(self) -> list[str]:
        """What this key can actually reach. Used to explain a bad model ID."""
        try:
            return sorted(m.name.removeprefix("models/")
                          for m in self._client.models.list())
        except Exception:                                # pragma: no cover
            return []

    def write(self, system: str, prompt: str, tokens: list[str]) -> str:
        try:
            response = self._client.models.generate_content(
                model=self.model,
                contents=prompt,
                config=self._types.GenerateContentConfig(
                    system_instruction=system,
                    temperature=TEMPERATURE,
                ),
            )
        except Exception as exc:
            hint = ""
            if "not found" in str(exc).lower() or "404" in str(exc):
                seen = self.available_models()
                flash = [m for m in seen if "flash" in m]
                hint = (f"\n\nModel '{self.model}' was rejected. Models this key "
                        f"can see:\n  " + "\n  ".join(flash or seen[:20]) +
                        "\n\nSet a working one in report/llm.py "
                        "(DEFAULT_GEMINI_MODEL).")
            raise WriterError(f"Gemini call failed: {exc}{hint}") from exc

        text = (response.text or "").strip()
        if not text:
            raise WriterError(
                "Gemini returned empty text. This usually means the response "
                "was blocked by a safety filter or the token budget was hit.")
        return text


BACKENDS = {"gemini": GeminiWriter, "stub": StubWriter, "rogue": RogueWriter}


def get_writer(name: str | None = None):
    """Pick a backend, announcing the choice.

    With no argument: Gemini when a key is present, stub otherwise. A missing
    key is a normal state here, not an error — the pipeline is designed to run
    and be tested without one.
    """
    if name:
        if name not in BACKENDS:
            raise WriterError(f"Unknown backend {name!r}. "
                              f"Choose from {sorted(BACKENDS)}.")
        writer = BACKENDS[name]()
        print(f"[llm] backend: {writer.name}")
        return writer

    if os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY"):
        writer = GeminiWriter()
        print(f"[llm] backend: gemini ({writer.model})")
        return writer

    print("[llm] backend: stub — no GEMINI_API_KEY set, so no real prose will "
          "be written.\n"
          "      Get a free key at https://aistudio.google.com/apikey and put "
          "it in .env to generate for real.")
    return StubWriter()
