"""
Fetch the official GRI Standards and extract their requirement text.
====================================================================

WHY
    CLAUDE.md §3: the STARS→GRI mapping is built against the real standards and
    never generated by a model. Titles alone are not enough to check a mapping
    — "305-1 Direct (Scope 1) GHG emissions" does not tell you that GRI also
    demands the gases included, biogenic CO2 separately, the base year, the
    emission factors and the consolidation approach.

    This script pulls that requirement text so a mapping row can be checked
    against what the standard actually says.

VERBATIM, NEVER SUMMARISED
    No model touches the extraction path. The requirement text is lifted
    element-by-element out of GRI's own HTML with BeautifulSoup, exactly the
    way the STARS scrapers work. The only transformation is collapsing
    whitespace — formatting, not rewording.

    Asking an LLM to "describe what 305-1 requires" would produce something
    authoritative-looking and unverifiable, which is precisely the failure §3
    exists to prevent. tests/test_gri_requirements.py asserts every stored
    line appears verbatim in the cached source.

OUTPUT
    standards/gri/pages/*.html    cached source (gitignored)
    standards/gri/*.pdf|.txt      the two PDFs, where a page is not enough
    standards/gri_requirements.json   extracted text (gitignored — GRI's
                                      copyrighted content, regenerable)

    gri_disclosures.json (committed) keeps only the short titles, which are
    identifiers you would cite anyway.

RUN
    python standards/fetch_gri.py              fetch pages + extract text
    python standards/fetch_gri.py --pdfs       also download the two PDFs
    python standards/fetch_gri.py --list       show what is on disk
"""

from __future__ import annotations

import argparse
import datetime
import json
import pathlib
import re
import subprocess
import sys
import time
import urllib.request

from bs4 import BeautifulSoup

DATE_STAMP = datetime.date.today().isoformat()

HERE = pathlib.Path(__file__).resolve().parent
GRI_DIR = HERE / "gri"
PAGES_DIR = GRI_DIR / "pages"
DISCLOSURES_JSON = HERE / "gri_disclosures.json"
REQUIREMENTS_JSON = HERE / "gri_requirements.json"

# GRI publishes the full text of every standard as an HTML page. All twelve
# were confirmed to return 200 — so one extraction path covers everything, and
# GRI 301/308 no longer need the secondary source they were first cited from.
PUBLICATION_SLUGS = {
    "GRI 2": "gri-2-general-disclosures-2021",
    # GRI 3 is UNIVERSAL — every GRI report answers 3-1/3-2/3-3, whatever its
    # topics. It was missing here until 2026-08-29, so the content index headed
    # "with reference to the GRI Standards" did not list the disclosures that
    # decide which standards apply. §16's lesson one level up: a completeness
    # check that only walks your own list cannot find what your list forgot —
    # and that was applied to disclosures within the chosen standards, never to
    # the set of standards itself.
    "GRI 3": "gri-3-material-topics-2021",
    "GRI 202": "gri-202-market-presence-2016",
    "GRI 204": "gri-204-procurement-practices-2016",
    "GRI 301": "gri-301-materials-2016",
    "GRI 302": "gri-302-energy-2016",
    "GRI 303": "gri-303-water-and-effluents-2018",
    "GRI 305": "gri-305-emissions-2016",
    "GRI 306": "gri-306-waste-2020",
    "GRI 308": "gri-308-supplier-environmental-assessment-2016",
    "GRI 401": "gri-401-employment-2016",
    "GRI 403": "gri-403-occupational-health-and-safety-2018",
    "GRI 405": "gri-405-diversity-and-equal-opportunity-2016",
}
PUBLICATION_BASE = ("https://www.globalreporting.org/publications/documents/"
                    "english")

DISCLOSURE_HEADING_RE = re.compile(r"^Disclosure (\d{1,3}-\d{1,2})\s+(.*)$")

# Guidance is explanatory, not normative, and roughly triples the volume.
# Everything up to it is what an organisation SHALL or SHOULD do.
GUIDANCE_MARKERS = ("guidance", "background", "glossary")

# standard number -> globalreporting.org pdf.ashx id.
# Only standards whose id has been confirmed by retrieval are listed; the rest
# of gri_disclosures.json was built from the publication pages, which carry the
# same text in HTML.
PDF_IDS = {
    "401": 12543,   # Employment 2016
    "403": 12565,   # Occupational Health and Safety 2018
}

URL = "https://www.globalreporting.org/pdf.ashx?id={}"
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

DISCLOSURE_RE = re.compile(r"Disclosure (\d{3}-\d{1,2}) ([A-Z][^|\n]{0,80})")


def download(number: str, pdf_id: int) -> pathlib.Path | None:
    GRI_DIR.mkdir(parents=True, exist_ok=True)
    target = GRI_DIR / f"gri-{number}.pdf"
    if target.exists() and target.stat().st_size > 0:
        print(f"[have] gri-{number}.pdf  "
              f"{target.stat().st_size / 1e6:.1f} MB")
        return target

    req = urllib.request.Request(URL.format(pdf_id),
                                 headers={"User-Agent": UA,
                                          "Accept": "application/pdf,*/*"})
    print(f"[fetch] GRI {number} (id={pdf_id})")
    try:
        with urllib.request.urlopen(req, timeout=120) as resp, \
                target.open("wb") as out:
            while chunk := resp.read(1 << 20):
                out.write(chunk)
    except Exception as exc:                               # noqa: BLE001
        target.unlink(missing_ok=True)
        print(f"[warn] GRI {number} failed: {exc}")
        return None

    if target.read_bytes()[:4] != b"%PDF":
        print(f"[warn] GRI {number}: response was not a PDF — discarding")
        target.unlink(missing_ok=True)
        return None

    print(f"[ok]   gri-{number}.pdf  {target.stat().st_size / 1e6:.1f} MB")
    return target


def extract(pdf: pathlib.Path) -> list[tuple[str, str]]:
    """pdftotext -> the standard's disclosure inventory."""
    txt = pdf.with_suffix(".txt")
    try:
        subprocess.run(["pdftotext", "-layout", str(pdf), str(txt)],
                       check=True, capture_output=True)
    except FileNotFoundError:
        print("[warn] pdftotext not installed (apt install poppler-utils) — "
              "skipping text extraction")
        return []
    except subprocess.CalledProcessError as exc:
        print(f"[warn] pdftotext failed on {pdf.name}: {exc}")
        return []

    seen = {}
    for num, title in DISCLOSURE_RE.findall(txt.read_text(encoding="utf-8",
                                                          errors="replace")):
        title = re.sub(r"\s+", " ", title).strip().rstrip(".0123456789 ")
        # Keep the longest rendering of each title — the contents page often
        # truncates, the body section gives the full wording.
        if num not in seen or len(title) > len(seen[num]):
            seen[num] = title
    return sorted(seen.items())


# ----------------------------------------------------------------------
# publication pages — requirement text
# ----------------------------------------------------------------------
def fetch_page(standard: str, slug: str) -> str | None:
    """Cached GET of a GRI publication page."""
    PAGES_DIR.mkdir(parents=True, exist_ok=True)
    cache = PAGES_DIR / f"{slug}.html"
    if cache.exists() and cache.stat().st_size > 5000:
        return cache.read_text(encoding="utf-8", errors="replace")

    url = f"{PUBLICATION_BASE}/{slug}/"
    print(f"[fetch] {standard}: {slug}")
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    try:
        with urllib.request.urlopen(req, timeout=90) as resp:
            html = resp.read().decode("utf-8", errors="replace")
    except Exception as exc:                                   # noqa: BLE001
        print(f"[warn] {standard} failed: {exc}")
        return None

    cache.write_text(html, encoding="utf-8")
    time.sleep(1.0)                       # guest on someone else's server
    return html


def extract_requirements(html: str, standard: str) -> dict[str, dict]:
    """Pull each disclosure's normative text out of a publication page.

    GRI renders a standard as a flat document: an <h2> per disclosure, then the
    requirement paragraphs and list items until the next <h2>. Walking in
    document order and copying each element's text keeps it verbatim — nothing
    is rephrased, reordered or inferred.

    get_text() is called WITHOUT a separator on purpose: 'CO<sub>2</sub>' must
    come out as 'CO2', not 'CO 2'.
    """
    soup = BeautifulSoup(html, "lxml")
    for tag in soup(["script", "style", "nav", "header", "footer"]):
        tag.decompose()

    body = soup.find("div", class_="doc-body") or soup.body
    if body is None:
        return {}

    # GRI's own markup is not consistent: Disclosure 302-4 is a
    # <span class="heading"> where every other disclosure in the same document
    # is an <h2>. Promote those spans so the walk below sees them.
    #
    # ONLY THE OUTERMOST. These spans nest — the 302-4 heading is a
    # span.heading containing span.heading "Disclosure 302-4" and span.heading
    # "Reduction of energy consumption". Promoting all three made the two inner
    # ones look like non-disclosure headings that immediately cancelled the
    # disclosure the outer one had just opened, so 302-4 came out empty.
    heading_spans = body.find_all("span", class_=["heading", "h2"])
    nested = {id(s) for s in heading_spans}
    for span in heading_spans:
        if not any(id(a) in nested for a in span.parents):
            span.name = "h2"

    found: dict[str, dict] = {}
    current: str | None = None
    lines: list[str] = []
    in_guidance = False

    def flush():
        if current and lines:
            found[current]["text"] = "\n".join(lines).strip()

    for el in body.find_all(["h1", "h2", "h3", "p", "li"]):
        # A list item's get_text() swallows its nested sub-items, which are
        # then visited again in their own right — the same sentences twice.
        # Take only this element's own text and let the children speak for
        # themselves, which also preserves the a./i. hierarchy as line order.
        if el.name == "li":
            own = el.__copy__()
            for nested in own.find_all(["ul", "ol"]):
                nested.decompose()
            text = re.sub(r"\s+", " ", own.get_text()).strip()
        elif el.name in ("h1", "h2", "h3"):
            # Headings get a separator: some are built from adjacent child
            # elements that would otherwise concatenate into
            # "Disclosure 302-4Reduction of energy consumption" and fail the
            # heading regex. Headings contain no subscripts, so the separator
            # is safe here — unlike in body text, where it would break 'CO2'.
            text = re.sub(r"\s+", " ", el.get_text(" ")).strip()
        else:
            text = re.sub(r"\s+", " ", el.get_text()).strip()
        if not text:
            continue

        if el.name in ("h1", "h2"):
            m = DISCLOSURE_HEADING_RE.match(text)
            flush()
            lines, in_guidance = [], False
            if m:
                current = m.group(1)
                found[current] = {"title": m.group(2).strip(),
                                  "standard": standard,
                                  "text": ""}
            else:
                current = None
            continue

        if current is None:
            continue

        # A heading-like line naming guidance ends the normative part.
        if text.lower().rstrip(":") in GUIDANCE_MARKERS or \
                text.lower().startswith("guidance for"):
            in_guidance = True
        if in_guidance:
            continue

        lines.append(text)

    flush()
    return {k: v for k, v in found.items() if v["text"]}


def build_requirements() -> dict:
    disclosures = json.loads(DISCLOSURES_JSON.read_text(encoding="utf-8"))
    known = {num: (std, title)
             for std, body in disclosures["standards"].items()
             for num, title in body["disclosures"].items()}

    out, mismatches, missing = {}, [], []

    for standard, slug in PUBLICATION_SLUGS.items():
        html = fetch_page(standard, slug)
        if html is None:
            continue
        extracted = extract_requirements(html, standard)
        print(f"       {standard}: {len(extracted)} disclosures with text")

        for num, rec in extracted.items():
            rec["source_url"] = f"{PUBLICATION_BASE}/{slug}/"
            rec["cached_source"] = f"standards/gri/pages/{slug}.html"
            out[num] = rec
            # Cross-check the title we already trusted against GRI's own page.
            if num in known and known[num][1].lower() != rec["title"].lower():
                mismatches.append((num, known[num][1], rec["title"]))

    for num, (std, title) in known.items():
        if num not in out:
            missing.append(f"{num} ({std}) {title[:40]}")

    # The reverse check, and the more dangerous one. `missing` catches a
    # disclosure we list that GRI's page does not explain. `unlisted` catches a
    # disclosure GRI *defines* that our vocabulary never names — and that one is
    # silent, because nothing downstream can miss what it was never told about.
    # It found 8 mandatory General Disclosures (2-1..2-6, 2-25, 2-26) absent
    # from gri_disclosures.json, so the content index was not reporting them as
    # unanswered; it was omitting the questions.
    unlisted = [f"{num} ({rec['standard']}) {rec['title'][:40]}"
                for num, rec in out.items() if num not in known]

    return {"retrieved": DATE_STAMP,
            "requirements": out,
            "_mismatches": mismatches,
            "_missing": missing,
            "_unlisted": unlisted}


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--list", action="store_true",
                    help="show what is already downloaded and exit")
    ap.add_argument("--pdfs", action="store_true",
                    help="also download the two standards we hold as PDFs")
    args = ap.parse_args()

    if args.list:
        if not GRI_DIR.exists():
            print("nothing downloaded yet")
            return
        for f in sorted(GRI_DIR.iterdir()):
            print(f"  {f.name:22} {f.stat().st_size / 1e6:6.1f} MB")
        return

    if args.pdfs:
        for number, pdf_id in PDF_IDS.items():
            pdf = download(number, pdf_id)
            if pdf is not None:
                extract(pdf)

    result = build_requirements()
    reqs = result["requirements"]

    REQUIREMENTS_JSON.write_text(
        json.dumps({"_README": [
            "Requirement text lifted VERBATIM from GRI's own publication "
            "pages by standards/fetch_gri.py. No model rephrased any of it.",
            "GITIGNORED: this is GRI's copyrighted content. Regenerate with "
            "python standards/fetch_gri.py. Titles live in the committed "
            "gri_disclosures.json.",
            "Cite as: GRI <n>: <title>. Global Reporting Initiative. "
            "Retrieved " + DATE_STAMP + " from <source_url>.",
        ],
            "retrieved": result["retrieved"],
            "requirements": reqs},
            indent=2, ensure_ascii=False),
        encoding="utf-8")

    chars = sum(len(r["text"]) for r in reqs.values())
    print(f"\n[save] {len(reqs)} disclosures, {chars:,} chars "
          f"-> {REQUIREMENTS_JSON.name}")

    if result["_mismatches"]:
        print(f"\n[WARN] {len(result['_mismatches'])} title(s) disagree with "
              f"gri_disclosures.json:")
        for num, ours, theirs in result["_mismatches"]:
            print(f"   {num}\n     ours   : {ours}\n     GRI    : {theirs}")
    else:
        print("       every title matches gri_disclosures.json")

    if result["_missing"]:
        print(f"\n[note] {len(result['_missing'])} disclosure(s) had no "
              f"requirement text extracted:")
        for m in result["_missing"]:
            print(f"   {m}")

    if result["_unlisted"]:
        print(f"\n[WARN] {len(result['_unlisted'])} disclosure(s) GRI defines "
              f"are NOT in gri_disclosures.json — the content index cannot "
              f"even list them as unanswered. Add them:")
        for u in result["_unlisted"]:
            print(f"   {u}")


if __name__ == "__main__":
    sys.exit(main())
