"""
Download official GRI Standard PDFs and extract their disclosure lists.
=======================================================================

Replaces fetch_gri.sh + extract_disclosures.sh with one file.

WHY THESE PDFS EXIST IN THE REPO'S WORKFLOW
    CLAUDE.md §3: the STARS→GRI mapping is built against the real standards and
    never generated by a model. These are the primary sources every mapping row
    is checked against. gri_disclosures.json is the machine-readable summary;
    these PDFs are the authority behind it.

    The PDFs themselves are gitignored — they are GRI's documents, not ours to
    redistribute. This script re-fetches them on demand.

RUN
    python standards/fetch_gri.py            download + extract
    python standards/fetch_gri.py --list     show what is already on disk
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys
import urllib.request

HERE = pathlib.Path(__file__).resolve().parent
GRI_DIR = HERE / "gri"

# standard number -> globalreporting.org pdf.ashx id.
# Only standards whose id has been confirmed by retrieval are listed; the rest
# of gri_disclosures.json was built from the publication pages, which carry the
# same text in HTML.
PDF_IDS = {
    "401": 12543,   # Employment 2016
    "403": 12565,   # Occupational Health and Safety 2018
}

URL = "https://www.globalreporting.org/pdf.ashx?id={}"
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

DISCLOSURE_RE = re.compile(r"Disclosure (\d{3}-\d{1,2}) ([A-Z][^|\n]{0,80})")


def download(number: str, pdf_id: int) -> pathlib.Path | None:
    GRI_DIR.mkdir(parents=True, exist_ok=True)
    target = GRI_DIR / f"gri-{number}.pdf"
    if target.exists() and target.stat().st_size > 0:
        print(f"[have] gri-{number}.pdf  "
              f"{target.stat().st_size / 1e6:.1f} MB")
        return target

    req = urllib.request.Request(URL.format(pdf_id),
                                 headers={"User-Agent": UA,
                                          "Accept": "application/pdf,*/*"})
    print(f"[fetch] GRI {number} (id={pdf_id})")
    try:
        with urllib.request.urlopen(req, timeout=120) as resp, \
                target.open("wb") as out:
            while chunk := resp.read(1 << 20):
                out.write(chunk)
    except Exception as exc:                               # noqa: BLE001
        target.unlink(missing_ok=True)
        print(f"[warn] GRI {number} failed: {exc}")
        return None

    if target.read_bytes()[:4] != b"%PDF":
        print(f"[warn] GRI {number}: response was not a PDF — discarding")
        target.unlink(missing_ok=True)
        return None

    print(f"[ok]   gri-{number}.pdf  {target.stat().st_size / 1e6:.1f} MB")
    return target


def extract(pdf: pathlib.Path) -> list[tuple[str, str]]:
    """pdftotext -> the standard's disclosure inventory."""
    txt = pdf.with_suffix(".txt")
    try:
        subprocess.run(["pdftotext", "-layout", str(pdf), str(txt)],
                       check=True, capture_output=True)
    except FileNotFoundError:
        print("[warn] pdftotext not installed (apt install poppler-utils) — "
              "skipping text extraction")
        return []
    except subprocess.CalledProcessError as exc:
        print(f"[warn] pdftotext failed on {pdf.name}: {exc}")
        return []

    seen = {}
    for num, title in DISCLOSURE_RE.findall(txt.read_text(encoding="utf-8",
                                                          errors="replace")):
        title = re.sub(r"\s+", " ", title).strip().rstrip(".0123456789 ")
        # Keep the longest rendering of each title — the contents page often
        # truncates, the body section gives the full wording.
        if num not in seen or len(title) > len(seen[num]):
            seen[num] = title
    return sorted(seen.items())


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--list", action="store_true",
                    help="show what is already downloaded and exit")
    args = ap.parse_args()

    if args.list:
        if not GRI_DIR.exists():
            print("nothing downloaded yet")
            return
        for f in sorted(GRI_DIR.iterdir()):
            print(f"  {f.name:22} {f.stat().st_size / 1e6:6.1f} MB")
        return

    for number, pdf_id in PDF_IDS.items():
        pdf = download(number, pdf_id)
        if pdf is None:
            continue
        disclosures = extract(pdf)
        print(f"       {len(disclosures)} disclosures found:")
        for num, title in disclosures:
            print(f"         {num:8} {title[:64]}")


if __name__ == "__main__":
    sys.exit(main())
